### ISSUE TITLE
Set up HTTPS (requires new hosting?)

### ISSUE THREAD

**Issue by mcomella** [mcomella/mcomella.github.com#25]

**Comment by mcomella** [comment]
Consider Neocities: https://news.ycombinator.com/item?id=13024025

**Comment by mcomella** [comment]
Neocities would be $5/mo for SSL on a custom domain: https://neocities.org/supporter

**Comment by nmalkin** [comment]
Many people (myself included) set up HTTPS with Github Pages by [using Cloudflare](https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/) (which is admittedly kind of a hacky solution).

**Comment by mcomella** [comment]
@nmalkin Thanks for the thought. :) iiuc, on principle, I'm skeptical – part of HTTPS is end-to-end encryption guarantees and this solution breaks that by putting a third party in the middle, who is able to decrypt traffic as well as track it. When users visit my site, they choose to trust mcomella.xyz, but they don't choose to trust Cloudflare and this isn't transparent to them.

If I went for it anyway, sometimes trust can be gained by understanding motives – what is Cloudflare's incentive for providing free HTTPS services? Perhaps Github pays them for it? Perhaps they're hoping to get dedicated users for their CDN services? Or perhaps they're tracking traffic? With my minimal research, it's not very transparent and I'm not sure. :\

That being said, I've started to have a lot of skepticism about trust in software recently so maybe I'm being paranoid –  can I trust Github about hosting my content and not tracking users? [What are all these JS dependencies I download](https://hackernoon.com/im-harvesting-credit-card-numbers-and-passwords-from-your-site-here-s-how-9a8cb347c5b5)? Can I really opt out of all the data collection on my smartphone (or even my desktop OS now)? I guess I haven't even really seriously considered compiler backdoors... :P

**Comment by nmalkin** [comment]
Yeah, as you point out, we place a huge amount of trust in almost every part of the software ecosystem. Foregoing that trust entirely is intractable, and has been for a [long time](https://www.ece.cmu.edu/~ganger/712.fall02/papers/p761-thompson.pdf).

I agree that, by using a CDN, you are choosing to trust them. In fact, since they'll become your DNS provider, you're *really* trusting them. And yes, it's one extra party to trust, compared with TLS terminated at your servers. However, if the alternative is _no_ HTTPS, which implicitly trusts _everyone_ between the client and your host, it's still a significant improvement and thus may be worth it to many who are making this decision.


> When users visit my site, they choose to trust mcomella.xyz, but they don't choose to trust Cloudflare and this isn't transparent to them.

They're choosing to trust you and anyone you extend your trust to: your host, the third party libraries you use, the sketchy company powering credit card payments on your site. From a visitor's perspective, it doesn't really matter if Cloudflare has their information because you set it up as a man-in-the-middle, or because you decided to sell them your site's logs after the fact. Full transparency in data flows is sadly impossible to achieve.

With Cloudflare specifically, I can't speak to their motivations (and I think it's fair to question them). This feature isn't specific to GH Pages, however, so no, I don't think Github is paying them.

**Comment by mcomella** [comment]
That makes sense – your users trust you and who you choose to trust. Thanks for your input. :)

Looking at the Cloudflare pricing model, it looks like it's free up until certain usage limits:
- First 10,000 good requests are free and $0.05 per 10,000 good requests thereafter
- First 500k DNS requests are free. $.50 per every 500k DNS requests after.

If only I knew how much traffic my website actually got. :P

There also seems to be a difference between a "Universal SSL certificate" and a "Dedicated SSL certificate", which costs money.

Maybe their incentive to do free SSL is that they get to charge people when they upgrade their services or go over usage limits. 🤔

**Comment by mcomella** [comment]
GitHub now supports custom domains with HTTPS: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by mcomella** [comment]
Set up with GH. Note: www. still has some problems.
